# Generated by Django 6.0.4 on 2026-04-17 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('couples', '0002_couple_pair_and_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset_minutes', models.PositiveIntegerField()),
                ('channel', models.CharField(choices=[('in_app', 'In app'), ('push', 'Push'), ('email', 'Email')], max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='couples.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('event_id', 'user_id', 'offset_minutes'),
            },
        ),
        migrations.CreateModel(
            name='ScheduledNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('channel', models.CharField(choices=[('in_app', 'In app'), ('push', 'Push'), ('email', 'Email')], max_length=20)),
                ('dedupe_key', models.CharField(max_length=255, unique=True)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_notifications', to='couples.event')),
                ('reminder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_notifications', to='notifications.eventreminder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('scheduled_for', 'id'),
            },
        ),
        migrations.CreateModel(
            name='NotificationInbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('event_reminder', 'Event reminder'), ('event_updated', 'Event updated'), ('invite', 'Invite')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_notifications', to='couples.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_notifications', to=settings.AUTH_USER_MODEL)),
                ('scheduled_notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_entries', to='notifications.schedulednotification')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='eventreminder',
            index=models.Index(fields=['event', 'user'], name='notificatio_event_i_681bef_idx'),
        ),
        migrations.AddIndex(
            model_name='eventreminder',
            index=models.Index(fields=['user', 'is_enabled'], name='notificatio_user_id_12407e_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulednotification',
            index=models.Index(fields=['status'], name='notificatio_status_72284e_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulednotification',
            index=models.Index(fields=['scheduled_for'], name='notificatio_schedul_f5e18c_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulednotification',
            index=models.Index(fields=['status', 'scheduled_for'], name='notificatio_status_3ae76e_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulednotification',
            index=models.Index(fields=['user'], name='notificatio_user_id_b330ce_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulednotification',
            index=models.Index(fields=['event'], name='notificatio_event_i_c21071_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationinbox',
            index=models.Index(fields=['user'], name='notificatio_user_id_1b3c4a_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationinbox',
            index=models.Index(fields=['created_at'], name='notificatio_created_e910aa_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationinbox',
            index=models.Index(fields=['user', 'read_at'], name='notificatio_user_id_4561a6_idx'),
        ),
    ]
