# Generated by Django 6.0.4 on 2026-05-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationinbox_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationinbox',
            name='type',
            field=models.CharField(choices=[('event_reminder', 'Event reminder'), ('event_updated', 'Event updated'), ('event_created', 'Event created'), ('invite', 'Invite')], max_length=50),
        ),
    ]
