# Generated by Django 6.0.4 on 2026-05-08 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0005_trendlocation_enrichment_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='trendlocation',
            new_name='discovery_t_trend_s_4141d9_idx',
            old_name='discovery_t_trend_s_5db5bb_idx',
        ),
    ]
