# Generated by Django 6.0.4 on 2026-04-17 19:24

import random
import re
import string

from django.db import migrations, models


def _build_base(display_name, email):
    base = re.sub(r"[^a-z0-9]", "", (display_name or "").lower())
    if base:
        return base

    email_prefix = (email or "").split("@", 1)[0]
    base = re.sub(r"[^a-z0-9]", "", email_prefix.lower())
    return base or "user"


def _build_unique_code(base, existing_codes):
    while True:
        suffix = "".join(random.choices(string.ascii_lowercase + string.digits, k=4))
        candidate = f"{base}-{suffix}"
        if candidate not in existing_codes:
            existing_codes.add(candidate)
            return candidate


def backfill_user_codes(apps, schema_editor):
    User = apps.get_model("accounts", "User")

    existing_codes = set(
        User.objects.exclude(code__isnull=True)
        .exclude(code="")
        .values_list("code", flat=True)
    )

    users = User.objects.all().only("id", "display_name", "email", "code")
    for user in users:
        if user.code:
            continue

        base = _build_base(user.display_name, user.email)
        user.code = _build_unique_code(base, existing_codes)
        user.save(update_fields=["code"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=128, null=True),
        ),
        migrations.RunPython(backfill_user_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=128, unique=True),
        ),
    ]
